[package]
name = "sycamore-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
mapboxgl = { path = "../../" }
sycamore = "0.8.2"
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"

[dependencies.web-sys]
version = "0.3.60"
features = [
  "Window",
]

